SELECT * FROM EMPLOYEES e;

-- EMPLOYEES에서 first_name, last_name, job_id 컬럼만 조회
SELECT e.FIRST_NAME , e.LAST_NAME , e.JOB_ID FROM EMPLOYEES e;

-- EMPLOYEES에서 연봉이 12000 이상 되는 직원들의 LAST_NAME, SALARY 조회
SELECT e.LAST_NAME , e.SALARY 
FROM EMPLOYEES e
WHERE e.SALARY >= 12000;

-- 사원번호가 176인 직원의 LAST_NAME, DEPARTMENT_ID 조회
SELECT e.LAST_NAME , e.DEPARTMENT_ID
FROM EMPLOYEES e 
WHERE e.EMPLOYEE_ID = 176;

-- 연봉이 5000에서 12000 범위 이외인 사람들의 LAST_NAME, SALARY 조회
SELECT e.LAST_NAME , e.SALARY 
FROM EMPLOYEES e 
WHERE e.SALARY < 5000 OR e.SALARY > 12000;

-- 20번 OR 50번 부서에서 근무하는 모든 사원들의
-- LAST_NAME, DEPARTMENT_ID 오름차순
SELECT e.LAST_NAME , e.DEPARTMENT_ID
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID IN (20, 50)
ORDER BY e.LAST_NAME, e.DEPARTMENT_ID;

-- 커미션이 0보다 큰 사원들의 LAST_NAME, SALARY, COMMISSION_PCT 조회
-- 단, SALARY 내림차순, COMMISSION_PCT 내림차순
SELECT
	e.LAST_NAME ,
	e.SALARY ,
	e.COMMISSION_PCT
FROM
	EMPLOYEES e
WHERE
	e.COMMISSION_PCT > 0
ORDER BY
	e.SALARY DESC,
	e.COMMISSION_PCT DESC;

-- SALARY가 2500 OR 3500 OR 7000 이 아니며 JOB_ID가
-- SA_REP OR ST_CLERK 인 직원 조회
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	e.SALARY NOT IN (2500, 3500, 7000) AND e.JOB_ID IN ('SA_REP', 'ST_CLERK');

-- 2015년도에 고용된 직원 조회 후 입사일(HIRE_DATE) 기준으로 오름차순
SELECT *
FROM EMPLOYEES e 
WHERE e.HIRE_DATE >= '2015-01-01' AND e.HIRE_DATE <= '2015-12-31'
ORDER BY e.HIRE_DATE;

-- 20번 OR 50번 부서에서 근무하는 모든 사원들의
-- LAST_NAME, DEPARTMENT_ID 오름차순
-- 단, SALARY가 5000 ~ 12000 이하인
SELECT e.LAST_NAME , e.DEPARTMENT_ID 
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID IN (20, 50) AND e.SALARY BETWEEN 5000 AND 12000
ORDER BY e.LAST_NAME, e.DEPARTMENT_ID;


-- SALARY가 5000 ~ 12000 범위가 아닌 직원들의
-- LAST_NAME, SALARY 조회
SELECT e.LAST_NAME , e.SALARY 
FROM EMPLOYEES e 
WHERE e.SALARY NOT BETWEEN 5000 AND 12000;

-- 2015년도에 고용된 직원 조회
SELECT *
FROM EMPLOYEES e 
WHERE e.HIRE_DATE BETWEEN '2015-01-01' AND '2015-12-31';
