CREATE TABLE branch
(
  branch_id   NUMBER(10)    NOT NULL,
  branch_name VARCHAR2(50)  NOT NULL,
  branch_addr VARCHAR2(100) NOT NULL,
  library_id  NUMBER(10)    NOT NULL,
  CONSTRAINT PK_branch PRIMARY KEY (branch_id)
);

CREATE TABLE inventory
(
  inventory_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  stock_quantity NUMBER(10) NOT NULL,
  book_id        NUMBER(10) NOT NULL,
  branch_id      NUMBER(10) NOT NULL,
  CONSTRAINT PK_inventory PRIMARY KEY (inventory_id)
);

CREATE TABLE library
(
  library_id   NUMBER(10)   NOT NULL,
  library_name VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_library PRIMARY KEY (library_id)
);

CREATE TABLE loan_info
(
  loan_id      NUMBER(10) NOT NULL,
  loan_date    DATE       NOT NULL,
  due_date     DATE       NOT NULL,
  return_date  DATE      ,
  member_id    NUMBER(10) NOT NULL,
  inventory_id NUMBER(10) NOT NULL,
  CONSTRAINT PK_loan_info PRIMARY KEY (loan_id)
);

CREATE TABLE maru_book
(
  book_id          NUMBER(10)    NOT NULL,
  title            VARCHAR2(20)  NOT NULL,
  publisher        VARCHAR2(100) NOT NULL,
  publication_year NUMBER(4)     NOT NULL,
  CONSTRAINT PK_maru_book PRIMARY KEY (book_id)
);

CREATE TABLE maru_member
(
  member_id NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name      VARCHAR2(50) NOT NULL,
  birth     VARCHAR2(10) NOT NULL,
  phone     VARCHAR2(20) NOT NULL,
  joined_at DATE         NOT NULL,
  CONSTRAINT PK_maru_member PRIMARY KEY (member_id)
);

ALTER TABLE loan_info
  ADD CONSTRAINT FK_maru_member_TO_loan_info
    FOREIGN KEY (member_id)
    REFERENCES maru_member (member_id);

ALTER TABLE loan_info
  ADD CONSTRAINT FK_inventory_TO_loan_info
    FOREIGN KEY (inventory_id)
    REFERENCES inventory (inventory_id);

ALTER TABLE inventory
  ADD CONSTRAINT FK_maru_book_TO_inventory
    FOREIGN KEY (book_id)
    REFERENCES maru_book (book_id);

ALTER TABLE inventory
  ADD CONSTRAINT FK_branch_TO_inventory
    FOREIGN KEY (branch_id)
    REFERENCES branch (branch_id);

ALTER TABLE inventory
  ADD CONSTRAINT uk_maru_book_TO_branch UNIQUE (branch_id,book_id);

ALTER TABLE branch
  ADD CONSTRAINT FK_library_TO_branch
    FOREIGN KEY (library_id)
    REFERENCES library (library_id);


----------------------------
-- 한빛마트
----------------------------

-- 회원(hanbit_member)
-- member_id(varchar2(20)) pk, password(varchar2(20)), name(varchar2(20)), age(number(3)), grade(varchar2(10)), points(number(10))
-- grade는 default 값 : REGULAR, points default 0
-- age check 0보다 커야 한다
-- points check 0 이상이어야 한다
CREATE TABLE hanbit_member(
	member_id varchar2(20) NOT NULL,
	password varchar2(20) NOT NULL,
	name varchar2(20) NOT NULL,
	age number(3),
	grade varchar2(10) DEFAULT 'REGULAR',
	points number(10),
	CONSTRAINT PK_hanbit_member PRIMARY KEY (member_id),
	CONSTRAINT CK_member_AGE CHECK (age > 0),
	CONSTRAINT CK_member_POINTS CHECK (points >= 0)
);



-- 제조업체(manufacturer)
-- manufacturer_name varchar2(50) pk
-- phone varchar2(20)
-- location varchar2(100)
-- manager varchar2(20)
CREATE TABLE manufacturer(
	manufacturer_name varchar2(50) NOT NULL,
	phone varchar2(20) NOT NULL,
	location varchar2(100) NOT NULL,
	manager varchar2(20) NOT NULL,
	CONSTRAINT PK_manufacturer PRIMARY KEY (manufacturer_name)
);



-- product
-- product_id(varchar2(10)), product_name(100), stock_qty(10), unit_price(10), supply_date(date), supply_qty(10)
-- fk 주기
-- check stock_qty 0 이상이어야 한다
-- unit_price 0 보다 커야 한다.
CREATE TABLE product(
	product_id varchar2(20) NOT NULL,
	product_name varchar2(100) NOT NULL,
	stock_qty number(10) DEFAULT 0,
	unit_price number(10) NOT NULL,
	supply_date DATE DEFAULT SYSDATE,
	supply_qty number(10) NOT NULL,
	CONSTRAINT PK_product PRIMARY KEY (product_id),
	CONSTRAINT CK_product_STOCK CHECK (stock_qty > 0),
	CONSTRAINT CK_product_PRICE CHECK (unit_price > 0)
);
DROP TABLE PRODUCT;



-- post(게시글)
-- post_id(자동증가-pk), title(200) ,content(4000), post_date, 
-- fk 주기
CREATE TABLE post(
	post_id number(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	title varchar2(200) NOT NULL,
	content varchar2(4000) NOT NULL,
	post_date DATE NOT NULL,
	member_id varchar2(20) NOT NULL,
	CONSTRAINT PK_post_ID PRIMARY KEY (post_id)
);

DROP TABLE post;




-- hanbit_orders
-- order_id(자동증가-pk), order_qty, address, order_date
-- fk 주기
CREATE TABLE hanbit_orders(
	order_id number(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	order_qty number(10) NOT NULL,
	address varchar2(50) NOT NULL,
	order_date DATE DEFAULT SYSDATE,
	member_id varchar2(20) NOT NULL,
	product_id varchar2(20) NOT NULL,
	CONSTRAINT PK_hanbit_orders PRIMARY KEY (order_id),
	CONSTRAINT CK_orders_qty CHECK (order_qty > 0)
);

DROP TABLE hanbit_orders;

-- 제약조건

-- member_id, product_id 외래키 제약조건 추가
ALTER TABLE hanbit_orders
  ADD CONSTRAINT FK_hanbit_orders_TO_product
    FOREIGN KEY (product_id)
    REFERENCES PRODUCT (product_id);

ALTER TABLE hanbit_orders
  ADD CONSTRAINT FK_hanbit_orders_TO_member
    FOREIGN KEY (member_id)
    REFERENCES HANBIT_MEMBER (member_id);

-- post 테이블에 외래키 제약조건 추가
ALTER TABLE post
  ADD CONSTRAINT FK_post_TO_member
    FOREIGN KEY (member_id)
    REFERENCES HANBIT_MEMBER (member_id);
 
-- product 테이블에 외래키 제약조건 추가
ALTER TABLE PRODUCT ADD manufacturer_name varchar2(50) NOT NULL;
ALTER TABLE PRODUCT
  ADD CONSTRAINT FK_product_TO_manufacturer
    FOREIGN KEY (manufacturer_name)
    REFERENCES MANUFACTURER (manufacturer_name);



-- 가계부 기록 테이블(transactions)
-- tx_id : number, 자동증가, pk
-- tx_type : 수입 or 지출
-- amount : 금액
-- memo : 내역
-- reg_date : '2026-08-01'


CREATE TABLE transactions(
	tx_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tx_type varchar2(10) NOT NULL,
	amount number(10) NOT NULL,
	memo varchar2(2000),
	reg_date varchar2(20)
);

INSERT INTO transactions(tx_type,amount,memo,reg_date)
VALUES('수입',300000,'용돈','2026-08-01');

INSERT INTO transactions(tx_type,amount,memo,reg_date)
VALUES('수입',5000000,'급여','2026-08-10');

INSERT INTO transactions(tx_type,amount,memo,reg_date)
VALUES('지출',200000,'식대','2026-08-11');

-- tx_type 별 합계금액
SELECT t.TX_TYPE, sum(t.AMOUNT)
FROM TRANSACTIONS t 
GROUP BY t.TX_TYPE;

-- 월별 tx_type별 합계금액
